import React, { useState } from 'react';
import { View, Text, StyleSheet, ScrollView, Modal, TouchableOpacity } from 'react-native';
import { useTheme } from '../context/ThemeContext';
import { useData } from '../context/DataContext';
import Header from '../components/Header';
import CustomButton from '../components/CustomButton';
import BillView from '../components/BillView';
import { formatCurrency, formatDateTime } from '../utils/formatters';
import { GST_TYPES } from '../constants/gstRates';
import Icon from 'react-native-vector-icons/MaterialIcons';

const InvoiceDetailScreen = ({ navigation, route }) => {
  const { colors } = useTheme();
  const { updateInvoice, shopProfile } = useData();
  const [invoice, setInvoice] = useState(route.params.invoice);
  const [showBillModal, setShowBillModal] = useState(false);

  const togglePaymentStatus = async () => {
    const newStatus = invoice.status === 'paid' ? 'unpaid' : 'paid';
    const updatedInvoice = { ...invoice, status: newStatus };
    await updateInvoice(invoice.id, { status: newStatus });
    setInvoice(updatedInvoice);
  };

  const viewBill = () => {
    setShowBillModal(true);
  };

  const generateInvoiceText = () => {
    let text = `━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
    text += `           INVOICE\n`;
    text += `━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n`;

    if (shopProfile) {
      text += `${shopProfile.name}\n`;
      if (shopProfile.address) text += `${shopProfile.address}\n`;
      if (shopProfile.phone) text += `Phone: ${shopProfile.phone}\n`;
      if (shopProfile. gstNo) text += `GST: ${shopProfile.gstNo}\n`;
      text += `\n`;
    }

    text += `Invoice No: ${invoice.invoiceNo}\n`;
    text += `Date: ${formatDateTime(invoice.date)}\n`;
    text += `Status: ${invoice.status. toUpperCase()}\n\n`;

    text += `Customer: ${invoice.customerName || 'Walk-in'}\n`;
    if (invoice.customerPhone) text += `Phone: ${invoice.customerPhone}\n`;
    text += `\n━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
    text += `ITEMS\n`;
    text += `━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n`;

    invoice.items.forEach((item, index) => {
      text += `${index + 1}. ${item.name}\n`;
      text += `   ${formatCurrency(item.price)} × ${item.quantity}`;
      if (item.discount > 0) text += ` (${item.discount}% off)`;
      text += `\n`;
      text += `   GST: ${item.gstRate}%\n`;
      const itemTotal = item.price * item.quantity * (1 - item.discount / 100);
      text += `   Total: ${formatCurrency(itemTotal)}\n\n`;
    });

    text += `━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
    text += `SUMMARY\n`;
    text += `━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n`;

    const t = invoice.totals;
    text += `Subtotal: ${formatCurrency(t.subtotal)}\n`;
    if (t.billDiscountAmount > 0) {
      text += `Discount: -${formatCurrency(t.billDiscountAmount)}\n`;
    }

    if (invoice.gstType === GST_TYPES. CGST_SGST) {
      text += `CGST: ${formatCurrency(t. cgst)}\n`;
      text += `SGST: ${formatCurrency(t.sgst)}\n`;
    } else {
      text += `IGST: ${formatCurrency(t.igst)}\n`;
    }

    if (t.roundingAdjustment !== 0) {
      text += `Rounding: ${formatCurrency(t.roundingAdjustment)}\n`;
    }

    text += `\nGRAND TOTAL: ${formatCurrency(t.grandTotal)}\n`;
    text += `━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n`;
    text += `Thank you for your business!\n`;
    text += `Generated by BillCraft\n`;

    return text;
  };

  return (
    <View style={[styles.container, { backgroundColor: colors.background }]}>
      <Header
        title="Invoice Details"
        onBack={() => navigation.goBack()}
      />

      <ScrollView style={styles.content}>
        {/* Invoice Header Card */}
        <View style={[styles.headerCard, { backgroundColor: colors.card }]}>
          <View style={styles.headerRow}>
            <View style={styles.headerLeft}>
              <Text style={[styles.invoiceNo, { color: colors.primary }]}>
                {invoice.invoiceNo}
              </Text>
              <Text style={[styles.date, { color: colors.textSecondary }]}>
                {formatDateTime(invoice.date)}
              </Text>
            </View>
            <View style={styles.headerRight}>
              <View style={[
                styles.statusBadge,
                { backgroundColor: invoice.status === 'paid' ? colors.success : colors.warning }
              ]}>
                <Icon 
                  name={invoice.status === 'paid' ? 'check-circle' : 'schedule'} 
                  size={16} 
                  color="#FFF" 
                  style={{ marginRight: 4 }}
                />
                <Text style={styles.statusText}>{invoice.status.toUpperCase()}</Text>
              </View>
              <Text style={[styles.grandTotal, { color: colors.text }]}>
                {formatCurrency(invoice.totals.grandTotal)}
              </Text>
            </View>
          </View>
        </View>

        {/* Items */}
        <View style={[styles.card, { backgroundColor: colors.card }]}>
          <Text style={[styles.sectionTitle, { color: colors. text }]}>Items</Text>
          {invoice.items.map((item, index) => (
            <View key={item.id} style={[styles.item, { borderBottomColor: colors.border }]}>
              <View style={styles.itemHeader}>
                <Text style={[styles.itemName, { color: colors.text }]}>
                  {index + 1}. {item.name}
                </Text>
                <Text style={[styles.itemPrice, { color: colors.primary }]}>
                  {formatCurrency(item.price * item.quantity * (1 - item.discount / 100))}
                </Text>
              </View>
              <Text style={[styles.itemDetail, { color: colors.textSecondary }]}>
                {formatCurrency(item.price)} × {item.quantity}
                {item.discount > 0 && ` (${item.discount}% off)`}
              </Text>
              <Text style={[styles.itemDetail, { color: colors.textSecondary }]}>
                GST: {item.gstRate}%
              </Text>
            </View>
          ))}
        </View>

        {/* Totals */}
        <View style={[styles.card, { backgroundColor: colors.card }]}>
          <Text style={[styles.sectionTitle, { color: colors.text }]}>Bill Summary</Text>
          
          <View style={styles.totalRow}>
            <Text style={[styles.totalLabel, { color: colors.textSecondary }]}>Subtotal</Text>
            <Text style={[styles.totalValue, { color: colors.text }]}>
              {formatCurrency(invoice.totals.subtotal)}
            </Text>
          </View>

          {invoice.totals.billDiscountAmount > 0 && (
            <View style={styles.totalRow}>
              <Text style={[styles. totalLabel, { color: colors. textSecondary }]}>Discount</Text>
              <Text style={[styles.totalValue, { color: colors.error }]}>
                - {formatCurrency(invoice.totals.billDiscountAmount)}
              </Text>
            </View>
          )}

          {invoice.gstType === GST_TYPES.CGST_SGST ?  (
            <>
              <View style={styles. totalRow}>
                <Text style={[styles.totalLabel, { color: colors.textSecondary }]}>CGST</Text>
                <Text style={[styles.totalValue, { color: colors.text }]}>
                  {formatCurrency(invoice. totals.cgst)}
                </Text>
              </View>
              <View style={styles. totalRow}>
                <Text style={[styles.totalLabel, { color: colors.textSecondary }]}>SGST</Text>
                <Text style={[styles.totalValue, { color: colors.text }]}>
                  {formatCurrency(invoice. totals.sgst)}
                </Text>
              </View>
            </>
          ) : (
            <View style={styles.totalRow}>
              <Text style={[styles.totalLabel, { color: colors.textSecondary }]}>IGST</Text>
              <Text style={[styles.totalValue, { color: colors.text }]}>
                {formatCurrency(invoice.totals.igst)}
              </Text>
            </View>
          )}

          {invoice.totals.roundingAdjustment !== 0 && (
            <View style={styles.totalRow}>
              <Text style={[styles.totalLabel, { color: colors.textSecondary }]}>
                Rounding Adjustment
              </Text>
              <Text style={[styles.totalValue, { color: colors.text }]}>
                {formatCurrency(invoice.totals.roundingAdjustment)}
              </Text>
            </View>
          )}

          <View style={[styles.grandTotalRow, { borderTopColor: colors.border }]}>
            <Text style={[styles. grandTotalLabel, { color: colors.text }]}>Grand Total</Text>
            <Text style={[styles.grandTotalValue, { color: colors.primary }]}>
              {formatCurrency(invoice.totals.grandTotal)}
            </Text>
          </View>
        </View>

        {/* Actions */}
        <View style={styles.actions}>
          <CustomButton
            title="View Bill"
            onPress={viewBill}
            variant="primary"
            icon={<Icon name="receipt" size={20} color="#FFF" />}
            style={styles.fullButton}
          />
        </View>
        
        <View style={styles.actions}>
          <CustomButton
            title={invoice.status === 'paid' ? 'Mark as Unpaid' : 'Mark as Paid'}
            onPress={togglePaymentStatus}
            variant={invoice.status === 'paid' ? 'outline' : 'success'}
            style={styles.fullButton}
          />
        </View>
      </ScrollView>

      {/* Bill Modal */}
      <Modal
        visible={showBillModal}
        animationType="slide"
        onRequestClose={() => setShowBillModal(false)}>
        <View style={[styles.modalContainer, { backgroundColor: colors.background }]}>
          <View style={[styles.modalHeader, { backgroundColor: colors.primary }]}>
            <Text style={styles.modalTitle}>Invoice Preview</Text>
            <TouchableOpacity onPress={() => setShowBillModal(false)}>
              <Icon name="close" size={28} color="#FFF" />
            </TouchableOpacity>
          </View>
          <ScrollView style={styles.modalContent}>
            <BillView invoice={invoice} shopProfile={shopProfile} />
          </ScrollView>
        </View>
      </Modal>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    flex: 1,
    padding: 16,
  },
  headerCard: {
    padding: 20,
    borderRadius: 16,
    marginBottom: 16,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  headerLeft: {
    flex: 1,
  },
  headerRight: {
    alignItems: 'flex-end',
  },
  invoiceNo: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 4,
  },
  date: {
    fontSize: 14,
    marginTop: 2,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    marginBottom: 8,
  },
  statusText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
  },
  grandTotal: {
    fontSize: 24,
    fontWeight: '800',
    marginTop: 4,
  },
  card: {
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 12,
  },
  customerName: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 4,
  },
  detail: {
    fontSize: 14,
    marginTop: 4,
  },
  item: {
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  itemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  itemName: {
    fontSize: 16,
    fontWeight: '600',
    flex: 1,
  },
  itemPrice: {
    fontSize: 16,
    fontWeight: '700',
  },
  itemDetail: {
    fontSize: 14,
    marginTop: 2,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  totalLabel: {
    fontSize: 16,
  },
  totalValue: {
    fontSize: 16,
    fontWeight: '600',
  },
  grandTotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 12,
    marginTop: 12,
    borderTopWidth: 2,
  },
  grandTotalLabel: {
    fontSize: 18,
    fontWeight: '700',
  },
  grandTotalValue: {
    fontSize: 20,
    fontWeight: '700',
  },
  actions: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  actionButton: {
    flex: 1,
  },
  fullButton: {
    flex: 1,
  },
  modalContainer: {
    flex: 1,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 24,
    paddingHorizontal: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#FFF',
  },
  modalContent: {
    flex: 1,
  },
  modalActions: {
    padding: 16,
    paddingBottom: 32,
  },
});

export default InvoiceDetailScreen;